---
apiVersion: mistletoe.dev/v1alpha1
kind: MistResult
data:
  result: Err
  message: "Failed to parse input YAML"
---
apiVersion: mistletoe.dev/v1alpha1
kind: MistResult
data:
  result: Ok
  files:
    "namespace.yaml": |
      apiVersion: v1
      kind: Namespace
      metadata:
        name: my-namespace
    "resources/deployment.yaml": |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: my-nginx
        namespace: my-namespace
        labels:
          app: my-nginx
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: my-nginx
        template:
          metadata:
            labels:
              app: my-nginx
          spec:
            containers:
            - image: nginx
              name: nginx
              ports:
              - name: http
                containerPort: 80
    "resources/service.yaml": |
      apiVersion: v1
      kind: Service
      metadata:
        name: my-nginx
        namespace: my-namespace
        labels:
          app: my-nginx
      spec:
        selector:
          app: my-nginx
        ports:
        - name: http
          port: 80
          protocol: TCP
          targetPort: http
