[package]
name = "mistletoe-mariadb"
version = "0.1.2"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
base64 = "0.21"
indexmap = "2.1"
k8s-openapi = { version = "0.20", features = ["v1_28"] }
mistletoe-api = { version = "0.1.2", path = "../../mistletoe-api" }
mistletoe-bind = { version = "0.1.2", path = "../../mistletoe-bind" }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
wasm-bindgen = "0.2"
