[package]
name = "mistletoe-api"
version = "0.1.0"
edition = "2021"

[dependencies]
indexmap = { version = "2.1", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
indoc = "2.0"
serde_yaml = "0.9"
