[package]
name = "mistletoe-bind"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
once_cell = "1.19"
serde_yaml = "0.9"

[dependencies.mistletoe-api]
path = "../mistletoe-api"

[dependencies.mistletoe-macros]
path = "../mistletoe-macros"
